### PR TITLE
Changed default cost to a sliding scale based on Moore's Law

### PR DESCRIPTION
**Pull request by JoseJimeniz**

### CODE REVIEW

**Comment by JoseJimeniz** [comment]
You can change the owner to me; i **am** the the original author anyway.

**Comment by marcelocantos** [comment]
Actually, I can't, since you already have a repo with the same name. I think I'll just delete mine, so people can find yours instead.

**Comment by marcelocantos** [comment]
BTW, I'm not convinced this Moore's law thing is the right approach. You should figure out a way to make $/solution constant over time. Single-threaded performance hasn't tracked Moore's law for a long time.

**Comment by JoseJimeniz** [comment]
I thought about that (Intel's scaling out rather than up). On the other hand they are increasing the number of execution units (six in Sandybridge verses eight in Haswell).

Either way i realized that BCrypt got faster. And the standard has bumped to 12 behind my back.

**Pull request merged**
